remote_theme: tuur29/pages-themes-cayman
title: TU Berlin Event Camera Dataset for Rotational Motion
color:
  gradient_left: "#FF3333"
  gradient_right: "#155799"
  header: "#fff"
  android_theme: "#000" # this default to gradient_color
  link: "#1e6bb8" # this default to gradient_color
  section_title: "#159957" # this default to gradient_color

syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

github: 
  is_project_page: false

# twitter:
#   username: guillermogb
  
# About/contact
author:
  name:       Shuang Guo
#   url:        http://www.guillermogallego.es

# defaults:
#   - scope:
#       path: ""
#     values:
#       image:
#         path: /images/cvpr2023_eventvision_workshop.jpg
#         height: 630
#         width: 1200
